services:
  web:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules

  web-prod:
    build:
      context: .
      target: production
    ports:
      - '8080:80'
