services:
  web:
    build:
      context: .
      target: dev
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app
      - /app/node_modules

  web-prod:
    build:
      context: .
      target: production
    ports:
      - '8080:80'

  deploy:
    build:
      context: .
      target: deploy
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
      - GIT_USER_NAME=${GIT_USER_NAME:-GitHub Pages Deploy}
      - GIT_USER_EMAIL=${GIT_USER_EMAIL:-deploy@github.com}
    profiles:
      - deploy
